baseURL = 'https://david.krentzlin.me'
title = 'David Krentzlin'
enableRobotsTXT = true
theme = "hugo-theme-monochrome"

[taxonomies]
  context = 'contexts'
  kind = 'kinds'
  tag = 'tags'

[markup]
  defaultMarkdownHandler = 'goldmark'

[params]
author="David Krentzlin"
navbar_title="David Krentzlin"
footer="It's not about how you start, but how you finish. Finish strong!"

color_scheme="dark"
enable_toc=true
enable_collapsible_toc=true
enable_anchor_header=true
enable_math=true
enable_zooming_js=true
enable_site_search=true

enable_twitter_cards=false

[params.list_layout]
  enable_group_by_year = true 
  enable_show_date = true 
  enable_pagination = false 

[[menu.navbar]]
identifier="cv"
name="CV"
title="My CV"
url="/cv/"
weight=80

[[menu.navbar]]
identifier="projects"
name="Projects"
title="My Projects"
url="/projects/"
weight=90


[[menu.navbar]]
identifier="writing"
name="Writing"
title="Follow my ramblings, if you will "
url="/writing/"
weight=100

